[package]
name = "aoc_2023_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
crossbeam-queue = "0.3.8"
num_cpus = "1.16.0"
rayon = "1.8.0"
regex = "1.10.2"
